# Generated by Django 5.0.6 on 2024-07-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(default=0, max_length=100, primary_key=True, serialize=False)),
                ('course_trainer', models.CharField(blank=True, max_length=100)),
                ('course_objective', models.CharField(blank=True, max_length=255)),
                ('course_duration', models.DurationField(default=0)),
                ('course_description', models.TextField(blank=True)),
                ('pass_mark', models.IntegerField(default=0)),
                ('course_title', models.CharField(blank=True, max_length=100)),
                ('course_teacher', models.CharField(blank=True, max_length=100)),
                ('course_resources', models.CharField(blank=True, max_length=255)),
                ('teaching_assistant', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
