# Generated by Django 5.0.6 on 2024-06-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_code', models.PositiveSmallIntegerField()),
                ('course_instructor', models.CharField(max_length=20)),
                ('course_assigment', models.CharField(max_length=20)),
                ('course_level', models.IntegerField()),
            ],
        ),
    ]
